version: "3.9"

services:
  db:
    image: postgres
    container_name: status-postgres-db
    restart: always
    environment:
      POSTGRES_DB: status_management_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: StatusPostgres@123
    volumes:
      - postgres_status_data:/var/lib/postgresql/data
    ports:
      - 8013:5432

  redis:
    image: redis
    container_name: status-redis
    restart: always
    ports:
      - 6379:6379

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: status-django-backend
    restart: always
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./server:/app
    ports:
      - 8001:8000
    depends_on:
      - db
      - redis
    env_file:
      - .env

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: status-react-frontend
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 5173:5173
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  postgres_status_data:
